# Each `AbstractImputedVector` type gives a vector that combines original non-missing values
# (of type `S`) and a series of `Ni` imputed values (of type `T`)

abstract type AbstractImputedVector{Ni, S, T} <: AbstractVector{S} end  # not exported

# Currently there is only one type of `AbstractImputedVector` (`ImputedVector`). Future
# types might include binary or categorical imputed vectors, in which the raw data are
# binary or categorical and the imputation process generates probabilities of missing values
# taking each of these categorical values.

"""
    ImputedVector{Ni, S, T}

Vector of non-missing and imputed values.

`Ni` is the number of imputed values generated for each missing value in the original 
    dataset.

`ImputedVector` will most commonly be created with the function `impute`.

# Fields
- `original::Vector{<:Union{Missing, S}}`: vector of original (missing and non-missing) 
    values
- `missingindex::Vector{Int}`: indexes of missing values
- `imputedvalues::Vector{MVector{Ni, T}}`: imputed values
- `Nm::Int`: number of missing values
- `Np::Int`: number of imputed values, where `Np = Ni * Nm`
"""
struct ImputedVector{Ni, S, T} <: AbstractImputedVector{Ni, S, T} 
    original::Vector{<:Union{Missing, S}}
    missingindex::Vector{Int}
    imputedvalues::Vector{MVector{Ni, T}}
    Nm::Int 
    Np::Int

    function ImputedVector{Ni, S, T}(
        original, missingindex, imputedvalues, Nm, Np
    ) where {Ni, S, T}
        Ni * Nm == Np || _imputedvectorerror1(Ni, Nm, Np)
        Nm == length(imputedvalues) || _imputedvectorerror2(Nm, length(imputedvalues))
        return new{Ni, S, T}(original, missingindex, imputedvalues, Nm, Np)
    end
end

function ImputedVector{Ni}(
    original::AbstractVector{<:Union{Missing, S}}, missingindex, imputedvalues, Nm, Np
) where {Ni, S}
    T = _typeofsumdivided(S) 
    return ImputedVector{Ni, S, T}(original, missingindex, imputedvalues, Nm, Np)
end

"""
    imputedvector([rng::AbstractRNG, ]Ni::Integer, original; <keyword arguments>)

Initialize an `ImputedVector`. The `imputedvalues` generated by this function are simply a 
    sample of the non-missing values from the original dataset. To generate an 
    `ImputedVector` using multiple imputation by chained equations, use the function `impute`.

# Arguments
- `Ni::Integer`: number of imputed copies to produce for each missing value
- `original`: vector of missing and non-missing values (must have at least one non-missing 
    value)

# Keywords
The keyword arguments are used to pass values that have already been calculated in other 
    functions. The random number generator can be passed as either the first positional 
    argument or as a keyword argument.
- `Nm=automatic`: number of missing values
- `nmvector=automatic`: vector of non-missing members of `original`
- `rng=default_rng()`: random number generator
"""
function imputedvector(Ni::Integer, original; rng=default_rng(), kwargs...)
    return imputedvector(rng, Ni, original; kwargs...)
end

function imputedvector(
    rng::AbstractRNG, Ni::Integer, original; 
    Nm=automatic, nmvector=automatic,
)
    return _imputedvector(rng, Ni, original, nmvector, Nm)
end

function _imputedvector(rng::AbstractRNG, Ni::Integer, original, nmvector, ::Automatic)
    Nm = sum(ismissing.(original))
    return _imputedvector(rng, Ni, original, nmvector, Nm)
end

function _imputedvector(rng::AbstractRNG, Ni::Integer, original, ::Automatic, Nm::Integer)
    nmvector = _makenmvector(original)
    return _imputedvector(rng, Ni, original, nmvector, Nm)
end 

function _imputedvector(
    rng::AbstractRNG, Ni::Integer, original, nmvector::AbstractVector{S}, Nm::Integer
) where S
    length(nmvector) >= 1 || throw(ErrorException("Must have at least 1 non-missing value"))
    T = _typeofsumdivided(S) 
    missingindex = findall(ismissing, original)
    imputedvalues = [ 
        MVector{Ni, T}([ T(sample(rng, nmvector)) for _ ∈ 1:Ni ]) 
        for _ ∈ 1:Nm 
    ]
    Np = Ni * Nm 
    return ImputedVector{Ni, S, T}(original, missingindex, imputedvalues, Nm, Np)
end

_makenmvector(v::AbstractVector) = collect(skipmissing(v))
_makenmvector(iv::AbstractImputedVector) = _makenmvector(iv.original)

function _imputedvectorerror1(Ni, Nm, Np)
    throw(DimensionMismatch("Np ($Np) must be the product of Ni ($Ni) and Nm ($Nm)"))
end

function _imputedvectorerror2(Nm, len)
    em = "Nm ($Nm) must equal the length of the vector of imputedvalues ($len)"
    throw(DimensionMismatch(em))
end

nimputed(v::AbstractImputedVector) = v.Nm
nimputedsets(::AbstractImputedVector{Ni, S, T}) where {Ni, S, T} = Ni

"""
    isimputedvalue(v, i)

Return whether the value at index i in vector v is an imputed value.

# Examples
```
julia> v = imputedvector(3, [1, missing ])       
2-element ImputedVector{3, Int64, Float64}:
 1
  [1.0, 1.0, 1.0]

julia> isimputedvalue(v, 1)
false

julia> isimputedvalue(v, 2)
true
```
"""
isimputedvalue(v::AbstractImputedVector, i) = i ∈ v.missingindex

# manual hash and equals so that we don't simply get each struct equals missing 
function Base.:(==)(a::AbstractImputedVector, b::AbstractImputedVector)
    hash(a) == hash(b) || return false
    length(a) == length(b) || return false

    for i ∈ eachindex(a)
        a[i] == b[i] || return false 
    end

    return true 
end

function Base.hash(a::AbstractImputedVector{Ni, S, T}, h::UInt) where {Ni, S, T}
    x = hash(:AbstractImputedVector, h)
    x = hash(Ni, h)
    for s ∈ [ :original, :missingindex, :imputedvalues, :Nm, :Np ] 
        x = hash(getproperty(a, s), x)
    end
    return x
end

Base.iterate(v::AbstractImputedVector) = iterate(v, 1)

function Base.iterate(v::AbstractImputedVector, i::Integer) 
    x = getindex(v, i)
    if i == length(v) 
        i_n = nothing 
    else 
        i_n = i + 1
    end 
    return ( x, i_n )
end 

function Base.getindex(v::AbstractImputedVector, i::Integer) 
    if isimputedvalue(v, i)
        j = findfirst(x -> x == i, v.missingindex)
        return v.imputedvalues[j]
    else
        return v.original[i]
    end
end

Base.length(v::AbstractImputedVector) = length(v.original)
Base.size(v::AbstractImputedVector) = size(v.original)

"""
    elementquantile(v::AbstractImputedVector{Ni, S, T}, p; <keyword arguments>)

Compute quantiles from each imputed dataset.

Solution is returned as a `StaticArrays.SVector` of length `Ni`. All keyword arguments are 
    passed to `StatsBase.quantile`.
"""
function elementquantile(v::AbstractImputedVector{Ni, S, T}, p; kwargs...) where {Ni, S, T}
    Z = typeof((one(S) + one(T)) / 1)
    return SVector{Ni, Z}([ quantile(imputedvectorview(v, i), p; kwargs...) for i ∈ 1:Ni ])
end

"""
    quantile(v::AbstractImputedVector, p; <keyword arguments>)

Returns the arithmetic mean of the quantile(s) at probability `p` calculated for each 
    imputed dataset.

Keyword arguments are used for calculating the quantile(s) in each imputed dataset.

See also `elementquantile`.
"""
function StatsBase.quantile(v::AbstractImputedVector, p; kwargs...)
    return sum(elementquantile(v, p; kwargs...)) / nimputedsets(v)
end

function StatsBase.quantile(v::AbstractImputedVector, ps::Vector; kwargs...) 
    return [ quantile(v, p; kwargs...) for p ∈ ps ]
end
