# Each `AbstractImputedVector` type gives a vector that combines original non-missing values
# (of type `S`) and a series of `Ni` imputed values (of type `T`)

abstract type AbstractImputedVector{Ni, S, T} <: AbstractVector{S} end  # not exported

"""
    ImputedVector{Ni, S, T}

Vector of non-missing and imputed values.

`Ni` is the number of imputed values generated for each missing value in the original 
    dataset.

`ImputedVector` will most commonly be created with the function `impute`.

# Fields
- `original::Vector{<:Union{Missing, S}}`: vector of original (missing and non-missing) values
- `missingindex::Vector{Int}`: indexes of missing values
- `imputedvalues::Vector{MVector{Ni, T}}`: imputed values
- `Nm::Int`: number of missing values
- `Np::Int`: number of imputed values, where `Np = Ni * Nm`
"""
struct ImputedVector{Ni, S, T} <: AbstractImputedVector{Ni, S, T} 
    original::Vector{<:Union{Missing, S}}
    missingindex::Vector{Int}
    imputedvalues::Vector{MVector{Ni, T}}
    Nm::Int 
    Np::Int

    function ImputedVector{Ni, S, T}(
        original, missingindex, imputedvalues, Nm, Np
    ) where {Ni, S, T}
        Ni * Nm == Np || _imputedvectorerror1(Ni, Nm, Np)
        Nm == length(imputedvalues) || _imputedvectorerror2(Nm, length(imputedvalues))
        return new{Ni, S, T}(original, missingindex, imputedvalues, Nm, Np)
    end
end

function ImputedVector{Ni}(
    original, missingindex, imputedvalues, Nm, Np; 
    nmvector=_makenmvector(original)
) where Ni
    S = typeof(nmvector[1])
    T = _typeofsumdivided(S) 
    return ImputedVector{Ni, S, T}(original, missingindex, imputedvalues, Nm, Np)
end

"""
    imputedvector([rng::AbstractRNG, ]Ni::Integer, original; <keyword arguments>)

Initialize an `ImputedVector`. The `imputedvalues` generated by this function are simply a 
    sample of the non-missing values from the original dataset. To generate an 
    `ImputedVector` using multiple imputation by chained equations, use the function `impute`.

# Arguments
- `Ni::Integer`: number of imputed copies to produce for each missing value
- `original`: vector of missing and non-missing values (must have at least one non-missing vale)

# Keywords
The keyword arguments are used to pass values that have already been calculated in other 
    functions. The random number generator can also be passed as a keyword argument.
- `Nm=automatic`: number of missing values
- `nmvector=automatic`: vector of non-missing members of `original`
- `rng=default_rng()`: random number generator
"""
function imputedvector(Ni::Integer, original; rng=default_rng(), kwargs...)
    return imputedvector(rng, Ni, original; kwargs...)
end

function imputedvector(
    rng::AbstractRNG, Ni::Integer, original; 
    Nm=automatic, nmvector=automatic
)
    return _imputedvector(rng, Ni, original, nmvector, Nm)
end

function _imputedvector(rng::AbstractRNG, Ni::Integer, original, nmvector, ::Automatic)
    Nm = sum(ismissing.(original))
    return _imputedvector(rng, Ni, original, nmvector, Nm)
end

function _imputedvector(rng::AbstractRNG, Ni::Integer, original, ::Automatic, Nm::Integer)
    nmvector = _makenmvector(original)
    return _imputedvector(rng, Ni, original, nmvector, Nm)
end 

function _imputedvector(rng::AbstractRNG, Ni::Integer, original, nmvector, Nm::Integer)
    length(nmvector) >= 1 || throw(ErrorException("Must have at least 1 non-missing value"))
    S = typeof(nmvector[1])
    T = _typeofsumdivided(S) 
    missingindex = findall(ismissing, original)
    imputedvalues = [ 
        MVector{Ni, T}([ T(sample(rng, nmvector)) for _ ∈ 1:Ni ]) 
        for _ ∈ 1:Nm 
    ]
    Np = Ni * Nm 
    return ImputedVector{Ni, S, T}(original, missingindex, imputedvalues, Nm, Np)
end

_makenmvector(original) = collect(skipmissing(original))

# manual hash and equals so that we don't simply get each struct equals missing 
function Base.:(==)(a::AbstractImputedVector, b::AbstractImputedVector)
    if hash(a) != hash(b) 
        return false
    elseif a.Nm != b.Nm 
        return false 
    elseif a.Np != b.Np 
        return false
    elseif (a.missingindex) != (b.missingindex)
        return false 
    elseif (a.imputedvalues) != (b.imputedvalues)
        return false 
    elseif length(a) != length(b)
        return false
    end
    for i ∈ eachindex(a)
        if a[i] != b[i]  
            return false
        end 
    end
    return true 
end

function Base.hash(a::ImputedVector{Ni, S, T}, h::UInt) where {Ni, S, T}
    hash(
        Ni,
        hash(
            a.original, 
            hash(
                a.missingindex, 
                hash(
                    a.imputedvalues, 
                    hash(
                        a.Nm,
                        hash(
                            a.Np,
                            hash(:AbstractImputedVector, h)
                        )
                    )
                )
            )
        )
    )
end

Base.iterate(v::AbstractImputedVector) = iterate(v, 1)

function Base.iterate(v::AbstractImputedVector, i::Integer) 
    x = getindex(v, i)
    if i == length(v) 
        i_n = nothing 
    else 
        i_n = i + 1
    end 
    return ( x, i_n )
end 

function Base.getindex(v::AbstractImputedVector, i::Integer) 
    if isimputedvalue(v, i)
        j = findfirst(x -> x == i, v.missingindex)
        return v.imputedvalues[j]
    else
        return v.original[i]
    end
end

Base.length(v::AbstractImputedVector) = length(v.original)
Base.size(v::AbstractImputedVector) = size(v.original)

function _imputedvectorerror1(Ni, Nm, Np)
    throw(DimensionMismatch("Np ($Np) must be the product of Ni ($Ni) and Nm ($Nm)"))
end

function _imputedvectorerror2(Nm, len)
    em = "Nm ($Nm) must equal the length of the vector of imputedvalues ($len)"
    throw(DimensionMismatch(em))
end
